service: sqs-to-dynamodb

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  emPreparacaoToDynamoDB:
    handler: handler.em_preparacao_to_dynamodb
    events:
      - sqs:
          arn:
            arn:aws:sqs:us-east-1:981004968329:em-preparacao-pizzaria
          batchSize: 1
  prontoToDynamoDB:
    handler: handler.pronto_to_dynamodb
    events:
      - sqs:
          arn:
            arn:aws:sqs:us-east-1:981004968329:pronto-pizzaria
          batchSize: 1