service: s3-to-sqs

custom:
  bucket: pizzaria-33cld-pedidos

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

functions:
  getObject:
    handler: handler.handler
    events:
      - s3:
          bucket: pizzaria-33cld-pedidos
          event: s3:ObjectCreated:*
          existing: True
          rules:
            - prefix: em-preparacao/
      - s3:
          bucket: pizzaria-33cld-pedidos
          event: s3:ObjectCreated:*
          existing: True
          rules:
            - prefix: pronto/